### ISSUE TITLE
XSD Validation via Lookup Manager Not Working in BridgeLink 4.6.0 (Java access removed)

### ISSUE THREAD

**Issue by Arjun161201** [Innovar-Healthcare/BridgeLink#100]
**Issue Summary**

In BridgeLink 4.6.0, I am trying to validate XML (CCD/CCDA) against XSD schemas stored in Lookup Manager—including dependent XSDs referenced via **xs:import** and **xs:include.**

However, validation fails because Java access (**Java.type, Java.extend, LSResourceResolver,** etc.) appears to be fully disabled in 4.6.0, making multi-file XSD resolution impossible inside JavaScript transformers.

 **Environment**

BridgeLink Version: 4.6.0

Transformer Type: JavaScript

Goal: Validate XML using XSDs stored inside BridgeLink Lookup Manager

Dependencies: ABC.xsd, POCD.xsd, datatypes.xsd, voc.xsd, etc.

 **What I Tried**

Loaded XSD content from Lookup Manager using:

`var content = LookupHelper.get("SchemaFiles", "ABC.xsd", ttl);
`

Attempted to create StreamSource and set systemId:

```
var src = new javax.xml.transform.stream.StreamSource(reader);
src.setSystemId("ABC.xsd");

```

Attempted to implement LSResourceResolver using:

`var LS = Java.type("javax.xml.transform.ls.LSResourceResolver");
`

Tried resolving dependent schemas in Lookup Manager.

All of these approaches now fail with errors like:
"Java is not defined"
"JavaPackage ... is not a function"
"javax.xml.transform... not available"

This indicates BridgeLink 4.6.0 no longer exposes Java APIs to transformers.

 **Problem**

Because Java access is disabled:

Cannot create SchemaFactory

Cannot create multiple StreamSource inputs

Cannot assign systemId for resolving imports

Cannot implement LSResourceResolver

Therefore cannot validate CCD/CCDA against XSDs stored in Lookup Manager

Only file-system-based validation still works.

**Questions for BridgeLink Team**

1. Is XML → XSD validation (with imports/includes) still supported inside JavaScript transformers in 4.6.0?

    If yes, what is the recommended method now that Java is no longer accessible?

2. Is there any supported mechanism to resolve dependent XSDs stored in Lookup Manager?

        Example: ABC.xsd imports POCD.xsd, etc.

3. Was Java intentionally removed from the scripting engine in 4.6?

     If yes, is this documented anywhere?

4. What is the recommended alternative approach?

**Looking for clarification on the officially supported path.**

 **Goal**

Eliminate file-system-based XSD loading and validate XML using XSDs stored inside BridgeLink.

Need a way to perform full CCDA validation without relying on external file directories.

**Comment by Innovarzweng** [comment]
Hi @Arjun161201 

Would you please provide more details?
the code snippet or whole log trace.

Thanks,
Jim

**Comment by joshmc82** [comment]
Here is an example function to validate XML message string against an XSD (as a string):
```javascript
// Function to validate XML against XSD
function validateXML(xmlString, xsdString) {
	
	// Import required Java classes
	var SchemaFactory = Packages.javax.xml.validation.SchemaFactory;
	var StreamSource = Packages.javax.xml.transform.stream.StreamSource;
	var StringReader = Packages.java.io.StringReader;
	var SAXException = Packages.org.xml.sax.SAXException;
	
	try {
		// Create a SchemaFactory capable of understanding WXS schemas
		var factory = SchemaFactory.newInstance(Packages.javax.xml.XMLConstants.W3C_XML_SCHEMA_NS_URI);
		
		// Load the XSD schema
		var xsdReader = new StringReader(xsdString);
		var xsdSource = new StreamSource(xsdReader);
		var schema = factory.newSchema(xsdSource);
		
		// Create a validator from the schema
		var validator = schema.newValidator();
		
		// Validate the XML
		var xmlReader = new StringReader(xmlString);
		var xmlSource = new StreamSource(xmlReader);
		validator.validate(xmlSource);
		
		// If we get here, validation succeeded
		logger.info("XML validation successful");
		return true;
		
	} catch (e if e.javaException instanceof SAXException) {
		// Validation failed - SAXException contains the details
		logger.error("XML validation failed: " + e.javaException.getMessage());
		throw e;
		return false;
		
	} catch (e) {
		// Other errors (IO, parsing, etc.)
		logger.error("Error during validation: " + e);
		return false;
	}
}
```

Example Usage with DLG. This was tested against BridgeLink 4.6 running Java 17.

``` javascript
// Assuming your message is in XML format
var xmlContent = msg.toString();

// XSD as string - use your own XSD as appropriate
var xsdContent = LookupHelper.get("xsd", "shipOrder");
var isValid = validateXML(xmlContent, xsdContent);


// Handle validation result
if (!isValid) {
	// You can drop the message, send alert, route to error channel, etc.
	channelMap.put('validationError', 'true');
	// Or throw error to stop processing
	// throw new Error("XML validation failed");
}
```
Example XSD and XML message taken from https://www.w3schools.com/xml/schema_example.asp

**Comment by dsvanstedt** [comment]
@Arjun161201 - Are you still having issues with this? I tried Josh example and it worked without any problems.
